version: '3.5'

services:
  deploy:
    image: svenruppert/maven-3.5-jdk-oracle-11
    container_name: deploy
    hostname: deploy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $PWD/:/usr/src/mymaven
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ~/.gnupg/:/root/.gnupg/
    working_dir: /usr/src/mymaven
    #    command: 'mvn help:active-profiles
    command: 'mvn clean deploy
                    -P_release
                    -Dmaven.test.skip=true '